spring:
  datasource:
    url: jdbc:mysql://localhost:3306/babicakes?useTimezone=true&serverTimezone=UTC
    username: usermysql
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
