spring:
  datasource:
    url: jdbc:mysql://172.31.87.11:3306/babicakes?useTimezone=true&serverTimezone=UTC
    username: app_user
    password: r00tP@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

value:
  url:
    pix: https://api.openpix.com.br/api/openpix/v1/