spring:
  datasource:
    url: jdbc:mysql://3.94.79.242:3306/babicakes?useTimezone=true&serverTimezone=UTC
    username: thiago1
    password: Yh{#{y~-f06iC[pjgNZp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

value:
  url:
    pix: https://api.openpix.com.br/api/openpix/v1/

camel:
  component:
    quartz2:
      cron:
        v1: cron:tab?schedule=0/30+*+*+*+*+?

pageable:
  request:
    size: 150