spring:
  datasource:
    url: jdbc:mysql://localhost:3306/babicakes?useTimezone=true&serverTimezone=UTC
    username: usermysql
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

value:
  url:
    pix: https://api.openpix.com.br/api/openpix/v1/

camel:
  component:
    quartz2:
      cron:
        v1: cron:tab?schedule=0/30+*+*+*+*+?

#quartz2://myGroup/myTimerName?cron=0/2 0 0 ? * * *
#timer://foo?repeatCount=1

pageable:
  request:
    size: 150
