version: "3.7"

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: babicakes
      MYSQL_USER: 'usermysql'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"